name: Rust Build & UF2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5 # 升级到 v5

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: thumbv7em-none-eabihf
    
    - name: Install cargo-make
      run: cargo install --force cargo-make
    
    - name: Build UF2
      run: cargo make uf2 --release
    
    - name: Upload UF2
      uses: actions/upload-artifact@v4
      with:
        name: firmware-uf2
        path: rmk-config-dionysus_planck.uf2